// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sysloption/sysloption.proto

package sysloption

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CallRule struct {
	Call                 []string `protobuf:"bytes,1,rep,name=call,proto3" json:"call,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallRule) Reset()         { *m = CallRule{} }
func (m *CallRule) String() string { return proto.CompactTextString(m) }
func (*CallRule) ProtoMessage()    {}
func (*CallRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad34076d845c2f9e, []int{0}
}

func (m *CallRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallRule.Unmarshal(m, b)
}
func (m *CallRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallRule.Marshal(b, m, deterministic)
}
func (m *CallRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallRule.Merge(m, src)
}
func (m *CallRule) XXX_Size() int {
	return xxx_messageInfo_CallRule.Size(m)
}
func (m *CallRule) XXX_DiscardUnknown() {
	xxx_messageInfo_CallRule.DiscardUnknown(m)
}

var xxx_messageInfo_CallRule proto.InternalMessageInfo

func (m *CallRule) GetCall() []string {
	if m != nil {
		return m.Call
	}
	return nil
}

var E_Calls = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: ([]*CallRule)(nil),
	Field:         72299394,
	Name:          "sysl.calls",
	Tag:           "bytes,72299394,rep,name=calls",
	Filename:      "sysloption/sysloption.proto",
}

func init() {
	proto.RegisterType((*CallRule)(nil), "sysl.CallRule")
	proto.RegisterExtension(E_Calls)
}

func init() { proto.RegisterFile("sysloption/sysloption.proto", fileDescriptor_ad34076d845c2f9e) }

var fileDescriptor_ad34076d845c2f9e = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0xae, 0x2c, 0xce,
	0xc9, 0x2f, 0x28, 0xc9, 0xcc, 0xcf, 0xd3, 0x47, 0x30, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0x58, 0x40, 0x22, 0x52, 0x0a, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0xb1, 0xa4, 0xd2,
	0x34, 0xfd, 0x94, 0xd4, 0xe2, 0xe4, 0xa2, 0xcc, 0x82, 0x92, 0xfc, 0x22, 0x88, 0x3a, 0x25, 0x39,
	0x2e, 0x0e, 0xe7, 0xc4, 0x9c, 0x9c, 0xa0, 0xd2, 0x9c, 0x54, 0x21, 0x21, 0x2e, 0x96, 0xe4, 0xc4,
	0x9c, 0x1c, 0x09, 0x46, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x30, 0xdb, 0xca, 0x9d, 0x8b, 0x15, 0x44,
	0x17, 0x0b, 0xc9, 0xe9, 0x41, 0xcc, 0xd2, 0x83, 0x99, 0xa5, 0xe7, 0x9b, 0x5a, 0x92, 0x91, 0x9f,
	0xe2, 0x0f, 0xb6, 0xb5, 0x58, 0xa2, 0xe9, 0xf9, 0x1e, 0x25, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x3e,
	0x3d, 0x90, 0xd5, 0x7a, 0x30, 0x53, 0x83, 0x20, 0xfa, 0x9d, 0x78, 0xa3, 0xb8, 0x91, 0x5c, 0x99,
	0xc4, 0x06, 0x36, 0xc6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x55, 0x28, 0xb3, 0x46, 0xc5, 0x00,
	0x00, 0x00,
}
