name: Release

on:
  push:
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release protoc-gen-sysl
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}

      - name: Build :latest
        run: docker build -t anzbank/protoc-gen-sysl:latest .

      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push docker.io/anzbank/protoc-gen-sysl:latest